services:
  app:
    image: node:lts-alpine
    working_dir: /root
    volumes:
      - .:/root
    env_file:
      - .env.example
    ports:
      - 2875:2875
    entrypoint:
      - /bin/sh
      - -c
      - chmod u+x ./init.sh && ./init.sh $@
      - --
    command:
      - npm
      - run
      - dev
  npm:
    image: node:lts-alpine
    working_dir: /root
    volumes:
      - .:/root
    entrypoint:
      - npm
